from typing import TypedDict, List
from langchain_core.documents import Document




# state for the agent
class AdvisorState(TypedDict):
   query: str
   retrieved_docs: List[Document]
   reranked_docs: List[Document]
   response: dict
   route:str #"vector_db or rdbms"
   generated_sql:str #SQL generated by nl2sql
   sql_result:str #output of raw sql execution result



    # query: str
    # generated_sql: str
    # sql_result: str

    # query: str
    # retrieved_docs: List[Document]
    # reranked_docs: List[Document]
    # response: dict
    # route: str
